#include "ml_public_interface.h"

#include <iostream>
#include <chrono>
#include <ctime>
#include <iomanip>

// Generated by ChatGPT. Function that can be used within std::cout to print the current time of the computer.
std::ostream& time_now(std::ostream& os) {
    auto now = std::chrono::system_clock::now();
    std::time_t t = std::chrono::system_clock::to_time_t(now);
    std::tm* local_time = std::localtime(&t);
    return os << "  [" << std::put_time(local_time, "%H:%M") << "]";
}